-- Family Calendar schema (SQLite / Cloudflare D1). Idempotent: safe to re-run.
--
-- Timestamps are ISO-8601 UTC text ("2026-08-04T07:00:00.000Z"). Every write goes
-- through Date.toISOString(), so the format is fixed-width and lexicographic
-- comparison is chronological — which is what the date-range queries rely on.
-- Ids are generated by the application with crypto.randomUUID(), keeping the
-- schema free of dialect-specific functions.

create table if not exists children (
  id          text primary key,
  name        text not null,
  color       text not null default 'violet',
  emoji       text not null default '🙂',
  token       text not null unique,
  -- 'child'       -> uses the web app, gets push reminders
  -- 'participant' -> subscribes to a feed of the events they are on
  -- 'observer'    -> subscribes to a feed of everything
  kind        text not null default 'child',
  feed_token  text unique,
  last_fetched_at text,
  sort_order  integer not null default 0,
  created_at  text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

create table if not exists events (
  id         text primary key,
  child_id   text not null references children(id) on delete cascade,
  title      text not null,
  emoji      text not null default '📌',
  location   text,
  starts_at  text not null,
  ends_at    text not null,
  series_id  text,
  -- Shared by the rows of one multi-member activity. Null when only one
  -- member is on it. See docs/project.md 5.10.
  group_id   text,
  -- 'parent' or 'child'. A child's own entries never leave their own screen:
  -- the parent agenda and the adult feeds both filter to 'parent'.
  created_by text not null default 'parent',
  done_at    text,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

create index if not exists events_child_start_idx on events (child_id, starts_at);
create index if not exists events_start_idx on events (starts_at);
create index if not exists events_series_idx on events (series_id);
create index if not exists events_group_idx on events (group_id);

create table if not exists push_subscriptions (
  id         text primary key,
  child_id   text not null references children(id) on delete cascade,
  endpoint   text not null unique,
  p256dh     text not null,
  auth       text not null,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

create index if not exists push_child_idx on push_subscriptions (child_id);

-- Idempotency ledger for outbound notifications.
-- key is "lead:<event_id>" or "digest:<child_id>:<yyyy-mm-dd>".
create table if not exists notifications_sent (
  key     text primary key,
  sent_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- Failed parent logins, per client IP. A 6-digit PIN is only safe if guessing
-- is expensive, and Workers are stateless, so the counter has to live here.
create table if not exists login_attempts (
  ip           text primary key,
  failures     integer not null default 0,
  window_start text not null,
  locked_until text
);

-- Small key/value store for things the parent can change from the app rather
-- than from a terminal: the PIN hash, and the session epoch that revokes every
-- existing session when the PIN changes.
create table if not exists settings (
  key   text primary key,
  value text not null
);

-- A weekly repeat, kept alive indefinitely by topping up concrete occurrences.
--
-- materialised_through is the last date ever generated for this series, and
-- generation only ever appends *after* it. That is what makes the top-up safe:
-- deleting an occurrence can never cause it to be recreated, and re-running the
-- job produces nothing. The unique index on (series_id, starts_at) closes the
-- remaining gap — two runs racing each other cannot double-insert.
create table if not exists series (
  id                   text primary key,
  child_id             text not null references children(id) on delete cascade,
  title                text not null,
  emoji                text not null,
  location             text,
  start_time           text not null,   -- "15:00", wall clock in the family timezone
  end_time             text not null,   -- "16:00"
  materialised_through text not null,   -- YYYY-MM-DD
  group_id             text,            -- one row per member of a multi-member repeat
  active               integer not null default 1,
  created_at           text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

create index if not exists series_active_idx on series (active, materialised_through);
create unique index if not exists events_series_start_uidx on events (series_id, starts_at);

-- Which devices have opened a child's link. Not a security control: a device id
-- is a random number in a cookie, not a person, and it cannot block anything.
-- It answers the one question rotation cannot — has anyone else opened this? —
-- because a new device is rare where a new IP address is constant.
create table if not exists link_opens (
  device_id  text primary key,
  child_id   text not null references children(id) on delete cascade,
  first_seen text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  last_seen  text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  -- Null until a parent says "that was us". The first device to open a child's
  -- link is acknowledged on arrival, since it is the one that was expected.
  acknowledged_at text
);
create index if not exists link_opens_child_idx on link_opens (child_id);
